### ISSUE TITLE
git https backend missing

### ISSUE THREAD

**Issue by jadr2ddude** [panux/packages-main#12]
Error is:
```
fatal: Unable to find remote helper for 'https'
```
(Note: with openssl installed)

**Comment by jadr2ddude** [comment]
This requires porting over libcurl

**Comment by jadr2ddude** [comment]
This appears not to have fixed the issue. I think we may also need to enable an option for git to compile the https backend

**Comment by niaow** [comment]
Can we re-test this soon to see if this issue still applies?

**Comment by niaow** [comment]
Fixed. Needed to add missing dependencies.
