### ISSUE TITLE
Add strace/ltrace/gdb

### ISSUE THREAD

**Issue by niaow** [panux/packages-main#23]
We need these for debugging things

**Comment by vlinkz** [comment]
I made strace and gdb and added them to the repo. ltrace is going to take a little longer

**Comment by niaow** [comment]
Gdb doesnt work. It needs libpython (python 2) and expat

**Comment by vlinkz** [comment]
I noticed, I'll try to make those, but I leave on vacation in half an hour.

**Comment by niaow** [comment]
ok. i almost got python working. I can do it

**Comment by niaow** [comment]
gdb works (not using python or expat)

**Comment by niaow** [comment]
Bleh this is good enough
