### ISSUE TITLE
Add mkinitfs

### ISSUE THREAD

**Issue by niaow** [panux/packages-main#41]
Instead of creating out own system for generating initramfs's from scratch, I think we should either use [mkinitcpio](https://git.archlinux.org/mkinitcpio.git/tree/) (used in Arch) or [initramfs-tools](https://anonscm.debian.org/gitweb/?p=kernel/initramfs-tools.git) (on Debian/Ubuntu and others). On this issue, we should discuss which we should use and should add one of these.

**Comment by niaow** [comment]
So it seems that mkinitcpio heavily uses bash and has a lot of dependencies. We may just want to do initramfs-tools for now.

**Comment by niaow** [comment]
Initramfs-tools is probably better for us to use

**Comment by niaow** [comment]
I just looked in initramfs-tools, and it is very debian-specific. I think [mkinitfs](https://git.alpinelinux.org/cgit/mkinitfs/) from alpine should work best.

**Comment by vlinkz** [comment]
Done
